### ISSUE TITLE
Place to store data for past grading history

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#13]
Since most of this data goes poof into thin air when a new grading event occurs, it might be helpful to have a place to note past grading history data, with the grading event dates, grades assigned and past cert numbers.

I can't think of a great use case now, but allowing those past cert numbers to show up in searches could be useful.

**Comment by rising-sun-rarities** [comment]
I think it's useful to keep track of how many times a coin is submitted and when you submitted along with all the other info you mentioned. 

Will need to create a separate table in the db for grading history tied to the coin ID. In the coin view page a separate section for "grading events" should be added where the user can create a new event providing the TPG, submission number, type of submission, date of submission, and grade received. The system should then prompt the user if they want to update the coin info with the new cert number and grade.

**Comment by rising-sun-rarities** [comment]
Full submission tracking feature including auto update of grade/cert number and submission history has been implemented
