### ISSUE TITLE
Population data not showing up for one coin

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#16]
The individual coin page for my "Japan1765 5 Monme JNDA 09-46 Meiwa C-10 MS62" shows "N/A" for population data.  Other coins show the pop data, so this isn't 100% reproducible.

Might have been an import issue, as this was an early import.  LMK if I should try re-import, but filing in case it's a real issue.

<img width="969" alt="Screenshot 2024-12-24 at 8 52 32 AM" src="https://github.com/user-attachments/assets/cd30c83c-0c68-49f6-9ae9-16162978ac71" />

**Comment by dhun1849** [comment]
Pop data shows up correctly in list view for this coin.

**Comment by dhun1849** [comment]
To clarify, when I say "import" above, I mean "add coin".

**Comment by dhun1849** [comment]
The pop data no longer appears in list view either.  I could swear it was there yesterday.

**Comment by rising-sun-rarities** [comment]
Please try readding the coin, as i made some changes to pop logic last night when adding a new coin

**Comment by dhun1849** [comment]
Re-adding the coin now shows pop data, except for the top-pop numbers because it's zero (different issue).
