### ISSUE TITLE
Ability to add non-graded "raw" coins to inventory

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#20]
Multiple ways to enable this, one could be to add "None" or "Not Graded" or "Raw" option to Certification Service drop-down on Add New Coin page, which would allow manual entry of the coin similar to the "other" option suggested in:

https://github.com/rising-sun-rarities/numisnavigator-public/issues/19#issue-2758137471

**Comment by rising-sun-rarities** [comment]
The add coin page doesnt require a cert lookup, you can just enter the fields manually and save the coin for raw coins.
