### ISSUE TITLE
Add "weight" field to coin details

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#21]
I'm going crazy with the various fields, but I think we're almost there.  For coins with varying weight, such as Japanese mameita gin or Spanish cobs, it's important to note the weight.

It's possible to import this from PCGS for coins they've included the weight info, however they oddly list weight in the Pedigree field so I suggest just making this a manual entry option.  It's not all that common so shouldn't be too much of a burden to enter manually.

**Comment by rising-sun-rarities** [comment]
Weight, diameter, and edge added in commit 8a0f117
