### ISSUE TITLE
[Inventory List View] Enable grouping by sets

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#24]
From a collector standpoint, we often think in terms of groups of coins.  Some examples:

"Core Collection"
"Silver bar registry set"
"Gold bar registry set"
"Dupes to hold"
"Dupes to sell"
"Coins from my grandpa"

Many collections are large enough that they become unruly, so grouping helps us organize and focus.  Enabling users to sort by collection grouping in list view would be awesome.  There could be a "Group" or "Collection" tag that would (could) be assigned to each coin, but I suggest to make this one more powerful in the following way:
- In list view, offer a dropdown menu near the top to easily filter the view to only show a specific group/collection
- When importing coins from a registry or spreadsheet, allow the user to automatically assign all coins from that import session to a specific grouping

There are likely more ways the collection grouping could be made useful.

**Comment by dhun1849** [comment]
Something to think about, I have a few examples where a single coin fits into multiple collections I'm building.  Do we allow a coin to be part of multiple groups?  Might be tougher to implement, but I think it's the right way to do it.  Curious what you think.

**Comment by rising-sun-rarities** [comment]
I think the best way is a tag system. A coin can have multiple tags and then there would be a way to easily filter by tag. 

So say you had a toned Keicho ichibu with a chopmark. You could give it three tags: gold bar set, chopped, and toned. 

It would show up if you filtered by any of those three tags, but it would also show up if you just wanted to show all of your toned and chopped coins.

**Comment by rising-sun-rarities** [comment]
Added 12/30
