### ISSUE TITLE
[Edit Coin] Status field incorrectly shows "Disposed"

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#25]
1. Click on coin in list to open the View Coin page
2. Click the Edit button, scroll down to Status field

You'll see the Status is set to "Disposed", although it's just displayed incorrectly.  The actual status isn't affected by this issue.

<img width="397" alt="Screenshot 2024-12-25 at 3 50 05 PM" src="https://github.com/user-attachments/assets/d62bbb9d-2466-46bd-b404-8e9785cc2503" />

<img width="725" alt="Screenshot 2024-12-25 at 3 50 26 PM" src="https://github.com/user-attachments/assets/04f91f6f-0eae-4033-9bdd-43e2a0321386" />

**Comment by rising-sun-rarities** [comment]
Fixed and also updated UI and added ability to reupdate from PCGS etc
