### ISSUE TITLE
[Edit Coin] Purchase Date field shows todays date instead of Purchase Date

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#26]
1. Click on coin in list, hit Edit Coin button
2. Scroll to Purchase Details and view Purchase Date

Expected:
Show Purchase Date, if one has been entered
Actual
Shows todays date

Appears to just not be populating this field on the Edit Coin page, doesn't actually impact previously entered data, even if you hit the Save Changes button

<img width="398" alt="Screenshot 2024-12-25 at 3 58 04 PM" src="https://github.com/user-attachments/assets/878dc7e4-a643-4063-8385-d7579ee39e91" />

<img width="322" alt="Screenshot 2024-12-25 at 3 58 21 PM" src="https://github.com/user-attachments/assets/87c89fc4-6859-4205-9f76-101f5571ec54" />

**Comment by rising-sun-rarities** [comment]
Fixed
