### ISSUE TITLE
[Add Coin] Hitting enter key with text and cursor in Cert Number field should execute Coin Lookup button

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#27]
1. Go to Add Coin page
2. Choose PCGS (or another TPGS)
3. Enter text into the Certification Number field
4. Hit ENTER key on keyboard

Expected:
Coin Lookup button is executed
Actual
Save button is executed, along with error dialog because I haven't entered all required fields.

<img width="897" alt="Screenshot 2024-12-25 at 4 24 48 PM" src="https://github.com/user-attachments/assets/996050e9-df06-4c86-9b61-1221900bce84" />

**Comment by rising-sun-rarities** [comment]
Fixed
