### ISSUE TITLE
[Edit Coin] Date entry is sometimes 1 day off

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#28]
1. Click Edit Coin button
2. (In this case, I had not entered a date so Purchase Date field was blank)
3. Enter 11/10/2015
4. Save Changes

Expected:
View coin page shows 11/10/2015
Actual:
View coin page shows 11/9/2015

This bug wasn't happening an hour ago =)

<img width="292" alt="Screenshot 2024-12-25 at 4 34 40 PM" src="https://github.com/user-attachments/assets/2bdfc60d-56c5-461e-9318-e8ee97469dfb" />

<img width="316" alt="Screenshot 2024-12-25 at 4 34 55 PM" src="https://github.com/user-attachments/assets/29c432be-6215-4a45-9d96-6b5ed691636a" />

**Comment by rising-sun-rarities** [comment]
Fixed
