### ISSUE TITLE
[Add Coin] Imported weight value from PCGS isn't accepted as valid if too many sig figs

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#29]
1. Add new coin with weight value imported from PCGS (example: cert 44715206)
2. Hit Save

Expected:
Coin is added successfully
Actual:
Coin is not added because weight value isn't valid

<img width="268" alt="Screenshot 2024-12-25 at 5 07 09 PM" src="https://github.com/user-attachments/assets/4d937882-fcb5-401c-9aac-87b94afe33b9" />

**Comment by dhun1849** [comment]
Edited to 13.53 and I was able to save, so looks like it's just a sig fig thing.

**Comment by rising-sun-rarities** [comment]
fixed
