### ISSUE TITLE
[Add coin] Weight value not saved

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#30]
1. Add Coin page, enter coin details including coin weight (ie. 13.53)
2. Save Coin

Expected:
Coin weight is saved and displayed on View Coin page and inventory list
Actual:
Coin weight is displayed as N/A on View Coin page and inventory list

<img width="762" alt="Screenshot 2024-12-25 at 5 17 59 PM" src="https://github.com/user-attachments/assets/fe1c39f6-7535-40ed-9c83-b53c2446830e" />

<img width="546" alt="Screenshot 2024-12-25 at 5 14 57 PM" src="https://github.com/user-attachments/assets/a8433785-3c90-4820-ad77-39d55d38f37c" />

**Comment by dhun1849** [comment]
Just noticed I see the same issue with Diameter field.

**Comment by rising-sun-rarities** [comment]
Fixed for both
