### ISSUE TITLE
Add metal type & metal composition fields

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#9]
There are times when I want to filter my sort to metal type, such as only silver or only gold.  I also like to see the composition, such as "90%" silver.  I'd suggest adding a single field for metal (gold, silver, copper, tin, etc) and one for composition (90% or .900).

This gets tricky for coins such as Japanese issues that are a good mix of alloys.  For those, a user could still select the predominant metal, usually silver or gold, and then the composition could simply be a percentage of whatever the predominant metal is (63% or .630)

**Comment by rising-sun-rarities** [comment]
Added in cbb1fd6
